### ISSUE TITLE
Improve deployment process experience

### ISSUE THREAD

**Issue by wkozyra95** [membraneframework/live_compositor#361]
- [x] https://github.com/membraneframework/video_compositor/issues/339
- [x] https://github.com/membraneframework/video_compositor/issues/338
- [x] https://github.com/membraneframework/video_compositor/pull/344
- [x] https://github.com/membraneframework/video_compositor/pull/335
- [x] https://github.com/membraneframework-labs/live_compositor_deployment/pull/1
- [ ] Documentation

**Comment by WojciechBarczynski** [comment]
@wkozyra95 Is it done? There is already #558, so I think see can close this one
