### ISSUE TITLE
Support offline processing with membrane

### ISSUE THREAD

**Issue by wkozyra95** [membraneframework/live_compositor#381]
- [x]  #380 
- [x] https://github.com/membraneframework/video_compositor/pull/392
- [x] delayed API requests
  - [x] scene updates with PTS https://github.com/membraneframework/video_compositor/pull/395
  - [x] register input at PTS 
  - [x] unregister input at PTS https://github.com/membraneframework/video_compositor/pull/395
  - [x] unregister output with PTS https://github.com/membraneframework/video_compositor/pull/395
- [x] RTP over TCP in compositor (input + output)
  - [x] input - https://github.com/membraneframework/video_compositor/pull/396
  - [x] output - https://github.com/membraneframework/video_compositor/pull/399
- [x] Add support for EOS packets
  - [x] https://github.com/membraneframework/video_compositor/pull/405
  - [x] https://github.com/membraneframework/video_compositor/pull/416
  - [x] https://github.com/membraneframework/video_compositor/pull/418
  - [x] https://github.com/membraneframework/video_compositor/pull/424
- [x] membrane plugin
  - [x] https://github.com/membraneframework/membrane_video_compositor_plugin/pull/161
  - [x] https://github.com/membraneframework/membrane_video_compositor_plugin/pull/162
  - [x] https://github.com/membraneframework/membrane_video_compositor_plugin/pull/167

**Comment by WojciechBarczynski** [comment]
@wkozyra95 Isn't this finished?
