### ISSUE TITLE
Docs roadmap

### ISSUE THREAD

**Issue by wkozyra95** [membraneframework/live_compositor#558]
Missing docs pages

- Get started
  - [x] Standalone
  - [x] Membrane framework (page exists but it needs to be filled)
- Guides (step-by-step instructions with code snippets)
  - [x] How to receive output stream (as input we can use mp4 here or gif)
  - [x] How to deliver input stream (mostly focus on RTP)
  - [x] Simple scene 
  - [ ] Simple audio config 
  - [ ] Simple transition (with View/Rescaller)
  - [ ] How to center text/views, overlays on top of other elements/...
  - [ ] Offline processing
  - [ ] Web renderer (move from Concepts section) 
- Deployment
  - [x] Requirements (hardware + software)
  - [already exists] Configuration
  - [ ] Docker
  - [x] AWS example

**Comment by wkozyra95** [comment]
There are few parts missing from that list, but general structure is there, so I'm closing this umbrella issue
