### ISSUE TITLE
Add Blackmagic DeckLink support

### ISSUE THREAD

**Issue by wkozyra95** [membraneframework/live_compositor#588]
- [x] POC
- [x] Rust <-> C++  bindings with decklink SDK
- [x] Support for raw input types(not encoded)
- [x] Add decklink input
- [x] Run pixel format conversion on GPU
- [x] Docs + figure out public API
- [x] ~~Update release process (capabilities behind feature flag disabled by default)~~
  - We do not provide binaries with DeckLink support, building from source is necessary
